export const OpenTalkMeetingStatus = {
    WAITING_TOPIC: 'WAITING_TOPIC',
    WAITING_HOST_REGISTER: 'WAITING_HOST_REGISTER',
    WAITING_HOST_SELECTION: 'WAITING_HOST_SELECTION',
    UPCOMING: 'UPCOMING',
    ONGOING: 'ONGOING',
    COMPLETED: 'COMPLETED',
    CANCELLED: 'CANCELLED',
    POSTPONED: 'POSTPONED'
}